### ISSUE TITLE
Docker swarm, 通过zookeeper得到rpc服务器地址后无法连接

### ISSUE THREAD

**Issue by nichliu** [sofastack/sofa-rpc-node#48]
container 的网络
eth0      Link encap:Ethernet  HWaddr 02:42:0A:FF:01:96
          inet addr:10.255.1.150  Bcast:10.255.255.255  Mask:255.255.0.0
          UP BROADCAST RUNNING MULTICAST  MTU:1450  Metric:1
          RX packets:164 errors:0 dropped:0 overruns:0 frame:0
          TX packets:118 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:18204 (17.7 KiB)  TX bytes:16597 (16.2 KiB)

eth1      Link encap:Ethernet  HWaddr 02:42:0A:00:2B:81
          inet addr:10.0.43.129  Bcast:10.0.43.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1450  Metric:1
          RX packets:994842 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1557577 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:88179528 (84.0 MiB)  TX bytes:124562996 (118.7 MiB)

eth0 被自动注册到zookeeper去了， 但是只有eth1 才能够顺利访问。
如何在注册的时候选择注册哪个网络啊?

**Comment by nichliu** [comment]
用Docker Swarm 部署， zookeeper 和 rpc server 都部署在同一网络。

2个container互相能够Ping 通，就是不能建立连接。但是看起来连接zookeeper倒是都没有问题

[AddressGroup] choosing 6 / 6 addresses for group=query:1.0@SOFA
  - bolt://10.255.8.101:8000?startTime=1559149254863&pid=1&uniqueId=&dynamic=true&appName=&timeout=3000&serialization=hessian2&weight=100&accepts=100000&language=nodejs&rpcVer=50400&protocol=&interface=query&version=1.0&group=SOFA
  - bolt://10.255.8.102:8000?startTime=1559149330283&pid=1&uniqueId=&dynamic=true&appName=&timeout=3000&serialization=hessian2&weight=100&accepts=100000&language=nodejs&rpcVer=50400&protocol=&interface=query&version=1.0&group=SOFA
  - bolt://10.255.8.105:8000?startTime=1559149556640&pid=1&uniqueId=&dynamic=true&appName=&timeout=3000&serialization=hessian2&weight=100&accepts=100000&language=nodejs&rpcVer=50400&protocol=&interface=query&version=1.0&group=SOFA
  - bolt://10.255.8.104:8000?startTime=1559149481210&pid=1&uniqueId=&dynamic=true&appName=&timeout=3000&serialization=hessian2&weight=100&accepts=100000&language=nodejs&rpcVer=50400&protocol=&interface=query&version=1.0&group=SOFA
  - bolt://10.255.8.103:8000?startTime=1559149405804&pid=1&uniqueId=&dynamic=true&appName=&timeout=3000&serialization=hessian2&weight=100&accepts=100000&language=nodejs&rpcVer=50400&protocol=&interface=query&version=1.0&group=SOFA
  - bolt://10.255.8.100:8000?startTime=1559149179357&pid=1&uniqueId=&dynamic=true&appName=&timeout=3000&serialization=hessian2&weight=100&accepts=100000&language=nodejs&rpcVer=50400&protocol=&interface=query&version=1.0&group=SOFA
[ConnectionManager] create connection: bolt://10.255.8.101:8000?startTime=1559149254863&pid=1&uniqueId=&dynamic=true&appName=&timeout=3000&serialization=hessian2&weight=100&accepts=100000&language=nodejs&rpcVer=50400&protocol=&interface=query&version=1.0&group=SOFA failed, caused by socket#bolt://10.255.8.101:8000?startTime=1559149254863&pid=1&uniqueId=&dynamic=true&appName=&timeout=3000&serialization=hessian2&weight=100&accepts=100000&language=nodejs&rpcVer=50400&protocol=&interface=query&version=1.0&group=SOFA connect timeout(3000ms)

[Wed May 29 2019 17:06:27 GMT+0000 (Coordinated Universal Time)][pid: 22][RpcClient] RpcSocketConnectTimeoutError: socket#bolt://10.255.8.101:8000?startTime=1559149254863&pid=1&uniqueId=&dynamic=true&appName=&timeout=3000&serialization=hessian2&weight=100&accepts=100000&language=nodejs&rpcVer=50400&protocol=&interface=query&version=1.0&group=SOFA connect timeout(3000ms)
Error Stack:
  RpcSocketConnectTimeoutError: socket#bolt://10.255.8.101:8000?startTime=1559149254863&pid=1&uniqueId=&dynamic=true&appName=&timeout=3000&serialization=hessian2&weight=100&accepts=100000&language=nodejs&rpcVer=50400&protocol=&interface=query&version=1.0&group=SOFA connect timeout(3000ms)
    at Socket.<anonymous> (/app/node_modules/sofa-rpc-node/lib/client/connection/rpc.js:81:19)
    at Object.onceWrapper (events.js:288:20)
    at Socket.emit (events.js:200:13)
    at Socket._onTimeout (net.js:432:8)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)

**Comment by nichliu** [comment]
publishAddress option fixed the issue
